mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.spark.model
  config-location: classpath:mybatis-config.xml

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    write:
      url: jdbc:mysql://10.10.92.10:3306/db_user?useUnicode=true&characterEncoding=utf8
      username: root
      password: 123456
      driverClassName: com.mysql.jdbc.Driver
    read:
      url: jdbc:mysql://127.0.0.1:3306/student?useUnicode=true&characterEncoding=utf8
      username: root
      password: 123456
      driverClassName: com.mysql.jdbc.Driver
